#!/bin/bash
#
# Setup environment to build RPM

set -euo pipefail

export LC_ALL=C

PACKAGER_DIR="$(cd "$(dirname "${0}")" && echo "${PWD}")"

# RPM macros
RPM_MACROS=/etc/rpm/macros.dist
RPM_DIST=.$(egrep -o "^%el[0-9]*" "${RPM_MACROS}" | tr -d '%')

# Setup build tools
echo
echo "# Setup build tools"
PACKAGE_MANAGER=""
if [[ "${RPM_DIST}" = ".el8" ]]; then
    echo "# - Install build tools for el8"
    dnf -y groupinstall "Development Tools"
    dnf -y install sudo wget git-core rpm-build rpmdevtools spectool yum-utils createrepo epel-release
    dnf -y install pinentry
    dnf config-manager --enable powertools
elif [[ "${RPM_DIST}" = ".el7" ]]; then
    echo "# - Remove centos vault repository"
    if [[ -f /etc/yum.repos.d/CentOS-Vault.repo ]]; then
        rm -f /etc/yum.repos.d/CentOS-Vault.repo /etc/yum.repos.d/CentOS-Sources.repo
    fi

    echo "# - Install build tools for el7"
    yum -y groupinstall "Development Tools"
    yum -y install sudo wget git-core rpm-build rpmdevtools spectool yum-utils createrepo epel-release
    yum clean all
fi

# Setup GHC environment
echo
echo "# Setup GHC environment"
${PACKAGER_DIR}/setup-ghc

