# generated by cabal-rpm-0.12.3
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name regex-pcre
%global pkgver %{pkg_name}-%{version}

Name:           ghc-%{pkg_name}
Version:        0.94.4
Release:        2%{?dist}
Summary:        Replaces/Enhances Text.Regex

License:        BSD
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-regex-base-devel
BuildRequires:  pcre-devel
# End cabal-rpm deps

%description
The PCRE backend to accompany regex-base, see www.pcre.org.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Begin cabal-rpm deps:
Requires:       pcre-devel%{?_isa}
# End cabal-rpm deps

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license LICENSE


%files devel -f %{name}-devel.files


%changelog
* Mon Apr 15 2019 Jun Futagawa <jfut@integ.jp> - 0.94.4-2
- Rebase spec file by cabal-rpm spec regex-pcre-0.94.4

* Mon Apr 15 2019 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.94.4-1
- spec file generated by cabal-rpm-0.12.3

* Thu May  8 2014 Jun Futagawa <jfut@integ.jp> - 0.94.4-1
- Removed ExclusiveArch
- Removed ghc_devel_package
- Added BuildRequires: ghc-compiler
- Added BuildRequires: ghc-regex-base-devel
- Added BuildRequires: pcre-devel
- Added Requires: ghc
- Added Requires: ghc-regex-base
- Added Requires: pcre

* Sun Apr 20 2014 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.5
