# generated by cabal-rpm-0.12.3
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name Crypto
%global pkgver %{pkg_name}-%{version}

Name:           ghc-%{pkg_name}
Version:        4.2.5.1
Release:        3%{?dist}
Summary:        Collects together existing Haskell cryptographic functions into a package

License:        Unknown
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  ghc-HUnit-devel
BuildRequires:  ghc-QuickCheck-devel
BuildRequires:  ghc-array-devel
BuildRequires:  ghc-pretty-devel
BuildRequires:  ghc-random-devel
# End cabal-rpm deps

%description
DES, Blowfish, AES, TEA, SHA1, MD5, RSA, BubbleBabble, Hexdump, Support for
Word128, Word192 and Word256 and Beyond, PKCS5 Padding, Various Encryption
Modes e.g. Cipher Block Chaining all in one package, with HUnit and QuickCheck
tests, and examples.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
%if %{defined ghc_version}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
%endif
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license ReadMe.tex
%{_datadir}/%{pkgver}


%files devel -f %{name}-devel.files
%{_bindir}/HMACTest
%{_bindir}/QuickTest
%{_bindir}/RSATest
%{_bindir}/SHA1Test
%{_bindir}/SymmetricTest
%{_bindir}/WordListTest


%changelog
* Mon Apr 15 2019 Jun Futagawa <jfut@integ.jp> - 4.2.5.1-3
- Rebase spec file by cabal-rpm spec Crypto-4.2.5.1

* Sat Apr 26 2014 Jun Futagawa <jfut@integ.jp> - 4.2.5.1-2
- Removed ghc_devel_package for Fedora 20

* Fri Feb  8 2013 Jun Futagawa <jfut@integ.jp> - 4.2.5.1-1
- Added BuildRequires: ghc-compiler
- Added BuildRequires: ghc-HUnit-devel
- Added Requires: ghc

* Wed Feb  6 2013 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.5
