name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-*

permissions:
  contents: read

jobs:
  release:
    name: Release on ${{ matrix.image }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - almalinux-10

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build RPM
        id: build_rpm
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/-/:/g') -a -bi
          echo "##[set-output name=release-tag;]$(echo ${{ github.ref }} | sed -e 's|refs/tags/||g')"

      - name: Upload Assets
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777 # v3.0
        with:
          files: "rpmbuild/*/SRPMS/*.rpm;rpmbuild/*/RPMS/*/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
