name: release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    name: Release on ${{ matrix.image }}
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: write

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - almalinux-10

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build RPM
        id: build_rpm
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/-/:/g') -a -bi

      - name: Upload Assets
        uses: AButler/upload-release-assets@34491005a5d7ec239a784e460807ce844fde7962 # v4.0.0
        with:
          files: "rpmbuild/*/SRPMS/*.rpm;rpmbuild/*/RPMS/*/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
