name: Build Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - 'doc/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    name: Build on ${{ matrix.image }}
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - almalinux-10

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build RPM
        id: build_rpm
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/-/:/g') -a -bi

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.image }}
          path: rpmbuild/**/*.rpm
