name: Build Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - 'doc/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    name: Build on ${{ matrix.image }}
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux-8
          - almalinux-9

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build RPM
        id: build_rpm
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/-/:/g') -a -bi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2 # v4.6.2
        with:
          name: ${{ matrix.image }}
          path: rpmbuild/**/*.rpm
